import {
  REACT_APP_BACKEND_DEV_URL,
  REACT_APP_BACKEND_PROD_URL,
  REACT_APP_API_KEY_DEV,
  REACT_APP_API_KEY_PROD,
  AUTH_DOMAIN_DEV,
  AUTH_DOMAIN_PROD,
  PROJECT_ID_DEV,
  PROJECT_ID_PROD,
  STORAGE_BUCKET_DEV,
  STORAGE_BUCKET_PROD,
  MESSAGING_SENDER_ID_DEV,
  MESSAGING_SENDER_ID_PROD,
  APP_ID_DEV,
  APP_ID_PROD,
  MEASUREMENT_ID_DEV,
  MEASUREMENT_ID_PROD
} from "@env";

const devEnvVariables = {
  BACKEND_URL: REACT_APP_BACKEND_DEV_URL,
  API_KEY: REACT_APP_API_KEY_DEV,
  AUTH_DOMAIN: AUTH_DOMAIN_DEV,
  PROJECT_ID: PROJECT_ID_DEV,
  STORAGE_BUCKET: STORAGE_BUCKET_DEV,
  MESSAGING_SENDER_ID: MESSAGING_SENDER_ID_DEV,
  APP_ID: APP_ID_DEV,
  MEASUREMENT_ID: MEASUREMENT_ID_DEV,
};

const prodEnvVariables = {
  BACKEND_URL: REACT_APP_BACKEND_PROD_URL,
  API_KEY: REACT_APP_API_KEY_PROD,
  AUTH_DOMAIN: AUTH_DOMAIN_PROD,
  PROJECT_ID: PROJECT_ID_PROD,
  STORAGE_BUCKET: STORAGE_BUCKET_PROD,
  MESSAGING_SENDER_ID: MESSAGING_SENDER_ID_PROD,
  APP_ID: APP_ID_PROD,
  MEASUREMENT_ID: MEASUREMENT_ID_PROD
};

export default __DEV__ ? devEnvVariables : prodEnvVariables;
